package org.patrick.learn.ignite.sql;
// Generated Apr 20, 2016 2:43:09 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.ignite.cache.query.annotations.QuerySqlField;

/**
 * CspSignal generated by hbm2java
 */
@Entity
@Table(name = "csp_signal", schema = "public")
public class CspSignal implements java.io.Serializable {

    private int    id;

    @QuerySqlField(index = true)
    private String vdsField;

    @QuerySqlField(index = true)
    private String vehicleModelCode;

    private String canSignal;

    @QuerySqlField(index = true)
    private int    canSignalValue;

    private String cspValue;

    private int    cspSignalValue;

    private String description;

    public CspSignal() {
    }

    public CspSignal(int id, String vdsField, String vehicleModelCode, int canSignalValue, String cspValue,
            int cspSignalValue) {
        this.id = id;
        this.vdsField = vdsField;
        this.vehicleModelCode = vehicleModelCode;
        this.canSignalValue = canSignalValue;
        this.cspValue = cspValue;
        this.cspSignalValue = cspSignalValue;
    }

    public CspSignal(int id, String vdsField, String vehicleModelCode, String canSignal, int canSignalValue,
            String cspValue, int cspSignalValue, String description) {
        this.id = id;
        this.vdsField = vdsField;
        this.vehicleModelCode = vehicleModelCode;
        this.canSignal = canSignal;
        this.canSignalValue = canSignalValue;
        this.cspValue = cspValue;
        this.cspSignalValue = cspSignalValue;
        this.description = description;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "vds_field", nullable = false, length = 2000)
    public String getVdsField() {
        return this.vdsField;
    }

    public void setVdsField(String vdsField) {
        this.vdsField = vdsField;
    }

    @Column(name = "vehicle_model_code", nullable = false, length = 200)
    public String getVehicleModelCode() {
        return this.vehicleModelCode;
    }

    public void setVehicleModelCode(String vehicleModelCode) {
        this.vehicleModelCode = vehicleModelCode;
    }

    @Column(name = "can_signal", length = 200)
    public String getCanSignal() {
        return this.canSignal;
    }

    public void setCanSignal(String canSignal) {
        this.canSignal = canSignal;
    }

    @Column(name = "can_signal_value", nullable = false)
    public int getCanSignalValue() {
        return this.canSignalValue;
    }

    public void setCanSignalValue(int canSignalValue) {
        this.canSignalValue = canSignalValue;
    }

    @Column(name = "csp_value", nullable = false, length = 200)
    public String getCspValue() {
        return this.cspValue;
    }

    public void setCspValue(String cspValue) {
        this.cspValue = cspValue;
    }

    @Column(name = "csp_signal_value", nullable = false)
    public int getCspSignalValue() {
        return this.cspSignalValue;
    }

    public void setCspSignalValue(int cspSignalValue) {
        this.cspSignalValue = cspSignalValue;
    }

    @Column(name = "description", length = 2000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("CspSignal [id=").append(id).append(", vdsField=").append(vdsField).append(", vehicleModelCode=")
                .append(vehicleModelCode).append(", canSignal=").append(canSignal).append(", canSignalValue=")
                .append(canSignalValue).append(", cspValue=").append(cspValue).append(", cspSignalValue=")
                .append(cspSignalValue).append(", description=").append(description).append("]");
        return builder.toString();
    }

}
